"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var user_controller_1 = require("../controllers/user.controller");
var auth_middleware_1 = require("../utils/auth.middleware");
var router = express_1.default.Router();
router.post('/createUser', auth_middleware_1.protect, (0, auth_middleware_1.authorize)(['HOD', 'ADMIN']), user_controller_1.createUser);
router.get('/getAllUsers', auth_middleware_1.protect, (0, auth_middleware_1.authorize)(['HOD', 'ADMIN']), user_controller_1.getAllUsers);
router.put('/updateUser', auth_middleware_1.protect, (0, auth_middleware_1.authorize)(['HOD', 'ADMIN']), user_controller_1.updateUserDepartmentId);
exports.default = router;
